# Generated by Django 5.1.1 on 2025-08-10 20:23

import django.db.models.deletion
import users.upload_paths
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type', models.CharField(choices=[('sick', 'Sick Leave'), ('bereavement', 'Bereavement Leave'), ('vacation', 'Vacation Leave'), ('other', 'Other Leave')], max_length=20)),
                ('approved', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payday', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payday'],
            },
        ),
        migrations.CreateModel(
            name='ShiftLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_in_photo', models.ImageField(blank=True, null=True, upload_to=users.upload_paths.PathAndRename('Clock_in_photo/'))),
                ('break_start', models.DateTimeField(blank=True, null=True)),
                ('break_start_photo', models.ImageField(blank=True, null=True, upload_to=users.upload_paths.PathAndRename('Break_start_photo/'))),
                ('break_end', models.DateTimeField(blank=True, null=True)),
                ('break_end_photo', models.ImageField(blank=True, null=True, upload_to=users.upload_paths.PathAndRename('Break_end_photo/'))),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('clock_out_photo', models.ImageField(blank=True, null=True, upload_to=users.upload_paths.PathAndRename('Clock_out_photo/'))),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_working_day', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
