# Generated by Django 5.1.1 on 2025-10-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
