# Generated by Django 5.1.1 on 2025-10-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_leaverequest_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='start_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
